import React from 'react';

export default ()=> {
    return (<div>
    Islam (/ˈɪslɑːm/[note 1]) is an Abrahamic monotheistic religion teaching that there is only one incomparable God (Allah)[1] and that Muhammad is the messenger of God.[2][3] It is the world's second-largest religion[4] and the fastest-growing major religion in the world,[5][6][7] with over 1.8 billion followers or 24.1% of the global population,[8] known as Muslims.[9] Muslims make up a majority of the population in 50 countries.[4] Islam teaches that God is merciful, all-powerful, unique,[10] and has guided mankind through prophets, revealed scriptures and natural signs.[3][11] The primary scriptures of Islam are the Quran, viewed by Muslims as the verbatim word of God, and the teachings and normative example (called the sunnah, composed of accounts called hadith) of Muhammad (c. 570–8 June 632 CE).

Muslims believe that Islam is the complete and universal version of a primordial faith that was revealed many times before through prophets including Adam, Abraham, Moses, and Jesus.[12][13][14] As for the Quran, Muslims consider it to be the unaltered and final revelation of God.[15] Like other Abrahamic religions, Islam also teaches a final judgment with the righteous rewarded paradise and unrighteous punished in hell.[16][17] Religious concepts and practices include the Five Pillars of Islam, which are obligatory acts of worship, and following Islamic law, which touches on virtually every aspect of life and society, from banking and welfare to women and the environment.[18][19] The cities of Mecca, Medina and Jerusalem are home to the three holiest sites in Islam.[20]

Apart from the Muslim viewpoint,[21][22][23] Islam is believed to have originated in the early 7th century CE in Mecca,[24] and by the 8th century the Islamic empire extended from Iberia in the west to the Indus River in the east. The Islamic Golden Age refers to the period traditionally dated from the 8th century to the 13th century when much of the historically Islamic world was experiencing a scientific, economic and cultural flourishing.[25][26][27] The expansion of the Muslim world involved various caliphates and empires, traders and conversion to Islam by missionary activities.[28]

Most Muslims are of one of two denominations:[29][30] Sunni (75–90%)[31] or Shia (10–20%).[32] About 13% of Muslims live in Indonesia,[33] the largest Muslim-majority country, 31% in South Asia,[34][35] the largest population of Muslims in the world,[36] 23% in the Middle East-North Africa,[37] where it is the dominant religion,[38] and 15% in Sub-Saharan Africa.[39][40][41] Sizable Muslim communities are also found in the Americas, Caucasus, China, Europe, Horn of Africa, Mainland Southeast Asia, Philippines, Russia and Swahili coast.[42]
Islam (Arabic: الإسلام‎‎, IPA: [alʔisˈlaːm] (About this sound listen)) is a verbal noun originating from the triliteral root S-L-M which forms a large class of words mostly relating to concepts of wholeness, submission, safeness, and peace.[43] In a religious context it means "voluntary submission to God".[44][45] Islām is the verbal noun of Form IV of the root, and means "submission" or "surrender". Muslim, the word for an adherent of Islam, is the active participle of the same verb form, and means "one who submits" or "one who surrenders". The word sometimes has distinct connotations in its various occurrences in the Quran. In some verses, there is stress on the quality of Islam as an internal state: "Whomsoever God desires to guide, He opens his heart to Islam."[46] Other verses connect Islām and dīn (usually translated as "religion"): "Today, I have perfected your religion (dīn) for you; I have completed My blessing upon you; I have approved Islam for your religion."[47] Still others describe Islam as an action of returning to God—more than just a verbal affirmation of faith.[48] In the Hadith of Gabriel, islām is presented as one part of a triad that also includes imān (faith), and ihsān (excellence).[49][50]

Islam was historically called Muhammadanism in Anglophone societies. This term has fallen out of use and is sometimes said to be offensive because it suggests that a human being rather than God is central to Muslims' religion, parallel to Jesus Christ in Christianity. Some authors, however, continue to use the term Muhammadanism as a technical term for the religious system as opposed to the theological concept of Islam that exists within that system.[51]

Concept of God
Main articles: God in Islam and Allah

Medallion showing the word "Allah" (God) in Hagia Sophia, Istanbul, Turkey.
Islam is often seen as having the simplest doctrines of the major religions.[6] Its most fundamental concept is a rigorous monotheism, called tawḥīd (Arabic: توحيد‎‎). God is described in chapter 112 of the Quran as: "Say, He is God, the One and Only; God, the Eternal, Absolute; He begetteth not, nor is He begotten; And there is none like unto Him" (112:1-4).[52] Muslims repudiate polytheism and idolatry, called Shirk, and reject the Christian doctrine of the Trinity and divinity of Jesus. In Islam, God is beyond all comprehension and Muslims are not expected to visualize God.[53][54][55][56] God is described and referred to by certain names or attributes, the most common being Al-Rahmān, meaning "The Compassionate" and Al-Rahīm, meaning "The Merciful" (See Names of God in Islam).[57]

Muslims believe that the creation of everything in the universe was brought into being by God's sheer command, "'Be' and so it is,"[58] and that the purpose of existence is to worship God.[59] He is viewed as a personal god who responds whenever a person in need or distress calls him.[60] There are no intermediaries, such as clergy, to contact God who states, "I am nearer to him than (his) jugular vein."[61] God consciousness is referred to as Taqwa.

Allāh is the term with no plural or gender used by Muslims and Arabic-speaking Christians and Jews to reference God, while ʾilāh (Arabic: إله‎‎) is the term used for a deity or a god in general.[62] Other non-Arab Muslims might use different names as much as Allah, for instance "Tanrı" in Turkish, "Khodā" in Persian or Ḵẖudā in Urdu.

Angels
Main article: Islamic view of angels

Islamic calligraphy of the Archangel Israfil (reflects upon how angels are most commonly represented in Islam).
Belief in angels is fundamental to the faith of Islam. The Arabic word for angel (Arabic: ملك‎‎ malak) means "messenger", like its counterparts in Hebrew (malʾákh) and Greek (angelos). According to the Quran, angels do not possess free will, and therefore worship and obey God in total obedience. Angels' duties include communicating revelations from God, glorifying God, recording every person's actions, and taking a person's soul at the time of death. Muslims believe that angels are made of light. They are described as "messengers with wings—two, or three, or four (pairs): He [God] adds to Creation as He pleases..."[63] Some scholars have emphasized a metaphorical reinterpretation of the concept of angels.[64] Pictorial depictions of angels are generally avoided in Islamic art, as the idea of giving form to anything immaterial is not accepted.[65] Muslims therefore do not generally share the perceptions of angelic pictorial depictions, such as those found in Western art.

Additionally, another kind of being that is sapient in Islam is called Jinn, who are believed to be invisible to humans, including the Satans.

Revelations
Main articles: Quran, Wahy, and Islamic holy books
See also: History of the Quran

The first chapter of the Quran, Al-Fatiha, consisting of seven verses.
The Islamic holy books are the records which most Muslims believe were dictated by God to various prophets. Muslims believe that parts of the previously revealed scriptures, the Tawrat (Torah) and the Injil (Gospels), had become distorted—either in interpretation, in text, or both.[66] The Quran (literally, "Reading" or "Recitation") is viewed by Muslims as the final revelation and literal word of God and is widely regarded as the finest literary work in the Arabic language.[67][68]

Muslims believe that the verses of the Quran were revealed to Muhammad by God through the archangel Gabriel (Jibrīl) on many occasions between 610 CE until his death on June 8, 632.[69] While Muhammad was alive, all of these revelations were written down by his companions (sahabah), although the prime method of transmission was orally through memorization.[70]

The Quran is divided into 114 suras, or chapters, which combined, contain 6,236 āyāt, or verses. The chronologically earlier suras, revealed at Mecca, are primarily concerned with ethical and spiritual topics. The later Medinan suras mostly discuss social and moral issues relevant to the Muslim community.[71]

The Quran is more concerned with moral guidance than legal instruction, and is considered the "sourcebook of Islamic principles and values".[72] Muslim jurists consult the hadith ("reports"), or the written record of Prophet Muhammad's life, to both supplement the Quran and assist with its interpretation. The science of Quranic commentary and exegesis is known as tafsir.[73] The set of rules governing proper pronunciation is called tajwid.

Muslims usually view "the Quran" as the original scripture as revealed in Arabic and that any translations are necessarily deficient, which are regarded only as commentaries on the Quran.[74]

Prophets and sunnah
Main articles: Prophets in Islam, Sunnah, and Hadith

The Arabic word for prophets preceded by the honorific "peace be upon them".
Muslims identify the prophets of Islam (Arabic: أنۢبياء‎‎ anbiyāʾ ) as those humans chosen by God to be his messengers. According to the Quran, the prophets were instructed by God to bring the "will of God" to the peoples of the nations. Muslims believe that prophets are human and not divine, though some are able to perform miracles to prove their claim. Islamic theology says that all of God's messengers preached the message of Islam—submission to the will of God. The Quran mentions the names of numerous figures considered prophets in Islam, including Adam, Noah, Abraham, Moses and Jesus, among others.[75]

Muslims believe that God finally sent Muhammad as the last law bearing prophet (Seal of the prophets) to convey the divine message to the whole world (to sum up and to finalize the word of God). In Islam, the "normative" example of Muhammad's life is called the Sunnah (literally "trodden path"). Muslims are encouraged to emulate Muhammad's actions in their daily lives and the Sunnah is seen as crucial to guiding interpretation of the Quran.[76] This example is preserved in traditions known as hadith, which recount his words, his actions, and his personal characteristics. Hadith Qudsi is a sub-category of hadith, regarded as verbatim words of God quoted by Muhammad but is not part of the Quran.

A hadith involves two elements- a chain of narrators, called sanad, and the actual wording, called matn. Hadiths can be classified, by studying the narration, as "authentic" or "correct", called Sahih (Arabic: صَحِيْح‎‎), "good", called Ḥasan (Arabic: حَسَن‎‎) or "weak", called Ḍaʻīf (Arabic: ضَعِيْف‎‎) among others. Muhammad al-Bukhari[77] collected over 300,000 hadith, but only included 2,602 distinct hadith that passed the tests that codified them as authentic into his book Sahih al-Bukhari,[77] which is considered by Sunnis to be the most authentic source after the Quran.[78][79] Another famous source(s) of hadiths is known as The Four Books, which Shias consider as the most authentic hadith reference.[80][81][82]

Resurrection and judgment
Main article: Qiyama
Belief in the "Day of Resurrection", Yawm al-Qiyāmah (Arabic: يوم القيامة‎‎) is also crucial for Muslims. They believe the time of Qiyāmah is preordained by God but unknown to man. The trials and tribulations preceding and during the Qiyāmah are described in the Quran and the hadith, and also in the commentaries of scholars. The Quran emphasizes bodily resurrection, a break from the pre-Islamic Arabian understanding of death.[83]

On Yawm al-Qiyāmah, Muslims believe all mankind will be judged on their good and bad deeds and consigned to Jannah (paradise) or Jahannam (hell). The Qurʼan in Surat al-Zalzalah describes this as, "So whoever does an atom's weight of good will see it (99:7) and whoever does an atom's weight of evil will see it (99:8)." The Qurʼan lists several sins that can condemn a person to hell, such as disbelief in God (Arabic: كفر‎‎ kufr), and dishonesty; however, the Qurʼan makes it clear God will forgive the sins of those who repent if he so wills. Good deeds, such as charity, prayer and compassion towards animals,[84][85] will be rewarded with entry to heaven. Muslims view heaven as a place of joy and blessings, with Qurʼanic references describing its features and the physical pleasures to come. Mystical traditions in Islam place these heavenly delights in the context of an ecstatic awareness of God.[86] Yawm al-Qiyāmah is also identified in the Quran as Yawm ad-Dīn (Arabic: يوم الدين‎‎), "Day of Religion";[87] as-sāʿah (Arabic: الساعة‎‎), "the Last Hour";[88] and al-Qāriʿah (Arabic: القارعة‎‎), "The Clatterer".[89]

Islamic apocalyptic literature describing Armageddon is often known as fitna or malahim. The Mahdi (prophesied redeemer) will be sent and with the help of Jesus, will battle the Antichrist. They will triumph, liberating Islam from cruelty, and this will be followed by a time of serenity with people living true to religious values.[90] 
    </div>);
};